package enc

import (
	cryptorand "crypto/rand"
	"encoding/base64"
	"errors"
	"io"
	"math/big"
	mathrand "math/rand"
)

// A PublicKey represents the public part of an RSA key.
//
// The values of N and E are not considered confidential, and may leak through
// side channels, or could be mathematically derived from other public values.
type RSAPublicKey struct {
	N *big.Int // modulus
	E int      // public exponent
}

// CRTValue contains the precomputed Chinese remainder theorem values.
type CRTValue struct {
	Exp   *big.Int // D mod (prime-1).
	Coeff *big.Int // R·Coeff ≡ 1 mod Prime.
	R     *big.Int // product of primes prior to this (inc p and q).
}

type PrecomputedValues struct {
	Dp, Dq *big.Int // D mod (P-1) (or mod Q-1)
	Qinv   *big.Int // Q^-1 mod P

	// CRTValues is used for the 3rd and subsequent primes. Due to a
	// historical accident, the CRT for the first two primes is handled
	// differently in PKCS #1 and interoperability is sufficiently
	// important that we mirror this.
	//
	// Deprecated: These values are still filled in by Precompute for
	// backwards compatibility but are not used. Multi-prime RSA is very rare,
	// and is implemented by this package without CRT optimizations to limit
	// complexity.
	CRTValues []CRTValue

	// fips *RSAPrivateKey
}
type RSAPrivateKey struct {
	RSAPublicKey            // public part.
	D            *big.Int   // private exponent
	Primes       []*big.Int // prime factors of N, has >= 2 elements.

	// Precomputed contains precomputed values that speed up RSA operations,
	// if available. It must be generated by calling PrivateKey.Precompute and
	// must not be modified.
	Precomputed PrecomputedValues
}

func modExp(base, exp, mod *big.Int) *big.Int {
	result := big.NewInt(1) // for big numbers
	base = new(big.Int).Mod(base, mod)
	for exp.Sign() > 0 {
		if new(big.Int).And(exp, big.NewInt(1)).Sign() != 0 {
			result = new(big.Int).Mul(result, base)
			result = new(big.Int).Mod(result, mod)
		}
		exp = new(big.Int).Rsh(exp, 1)
		base = new(big.Int).Mul(base, base)
		base = new(big.Int).Mod(base, mod)
	}
	return result
}

func gcd(a, b *big.Int) *big.Int {
	for b.Sign() > 0 {
		a, b = b, new(big.Int).Mod(a, b)
	}
	return a
}

func modInverse(a, m *big.Int) (*big.Int, error) {
	var g *big.Int = new(big.Int)
	var x *big.Int = new(big.Int)

	g, x, _ = extendedGCD(a, m)
	if g.Sign() != 1 {
		return nil, errors.New("modular inverse does not exist")
	}

	mod := new(big.Int).Mod(x, m)
	if mod.Sign() < 0 {
		mod = mod.Add(mod, m)
	}
	return mod, nil
}

func extendedGCD(a, b *big.Int) (*big.Int, *big.Int, *big.Int) {
	if b.Sign() == 0 {
		return a, big.NewInt(1), big.NewInt(0)
	}
	g, x1, y1 := extendedGCD(b, new(big.Int).Mod(a, b))
	x := y1
	y := new(big.Int).Sub(x1, new(big.Int).Mul(new(big.Int).Div(a, b), y1))
	return g, x, y
}

func millerRabin(n *big.Int, rounds int) bool {
	if n.Cmp(big.NewInt(2)) < 0 {
		return false
	}
	if n.Cmp(big.NewInt(2)) == 0 {
		return true
	}
	if new(big.Int).Mod(n, big.NewInt(2)).Sign() == 0 {
		return false
	}

	r := big.NewInt(0)
	d := new(big.Int).Sub(n, big.NewInt(1))
	for new(big.Int).Mod(d, big.NewInt(2)).Sign() == 0 {
		d = new(big.Int).Rsh(d, 1)
		r.Add(r, big.NewInt(1))
	}

	for i := 0; i < rounds; i++ {
		a := randomBigIntInRange(big.NewInt(2), new(big.Int).Sub(n, big.NewInt(2)))
		x := modExp(a, d, n)

		if x.Cmp(big.NewInt(1)) == 0 || x.Cmp(new(big.Int).Sub(n, big.NewInt(1))) == 0 {
			continue
		}

		composite := true
		for j := big.NewInt(0); j.Cmp(new(big.Int).Sub(r, big.NewInt(1))) < 0; j.Add(j, big.NewInt(1)) {
			x = modExp(x, big.NewInt(2), n)
			if x.Cmp(new(big.Int).Sub(n, big.NewInt(1))) == 0 {
				composite = false
				break
			}
		}
		if composite {
			return false
		}
	}
	return true
}

func randomBigIntInRange(min, max *big.Int) *big.Int {
	diff := new(big.Int).Sub(max, min)

	if diff.Sign() <= 0 {
		return new(big.Int).Set(min)
	}

	diff.Add(diff, big.NewInt(1))
	bytesNeeded := (diff.BitLen() + 7) / 8
	if bytesNeeded < 1 {
		bytesNeeded = 1
	}

	randomBytes := make([]byte, bytesNeeded)
	for {
		_, err := io.ReadFull(cryptorand.Reader, randomBytes)
		if err != nil {
			panic(err)
		}
		result := new(big.Int).SetBytes(randomBytes)
		if result.Cmp(diff) < 0 {
			return new(big.Int).Add(min, result)
		}
	}
}

func generatePrime(bitLen int) *big.Int {
	for {
		p := new(big.Int).Rand(mathrand.New(mathrand.NewSource(mathrand.Int63())), new(big.Int).Lsh(big.NewInt(1), uint(bitLen)))
		p.SetBit(p, bitLen-1, 1)
		p.Add(p, big.NewInt(1))
		if p.Bit(0) == 0 {
			p.Add(p, big.NewInt(1))
		}
		if millerRabin(p, 20) {
			return p
		}
	}
}

func GenerateKeyPair(bits int) (*RSAPrivateKey, *RSAPublicKey, error) {
	if bits < 8 || bits%2 != 0 {
		return nil, nil, errors.New("key size must be even and at least 8 bits")
	}

	primeBits := bits / 2

	p := generatePrime(primeBits)
	q := generatePrime(primeBits)

	for p.Cmp(q) == 0 {
		q = generatePrime(primeBits)
	}

	n := new(big.Int).Mul(p, q)
	phi := new(big.Int).Mul(new(big.Int).Sub(p, big.NewInt(1)), new(big.Int).Sub(q, big.NewInt(1)))

	e := big.NewInt(65537)

	if new(big.Int).Mod(phi, e).Sign() == 0 {
		e = big.NewInt(17)
	}
	if new(big.Int).Mod(phi, e).Sign() == 0 {
		e = big.NewInt(3)
	}

	d, err := modInverse(e, phi)
	if err != nil {
		return nil, nil, err
	}

	priv := &RSAPrivateKey{
		RSAPublicKey: RSAPublicKey{
			N: n,
			E: int(e.Int64()),
		},
		D:      d,
		Primes: []*big.Int{p, q},
	}

	pub := &RSAPublicKey{
		N: n,
		E: int(e.Int64()),
	}

	return priv, pub, nil
}

// the public key is used for the encryption
func Encrypt(pub *RSAPublicKey, msg []byte) ([]byte, error) {
	if len(msg) == 0 {
		return nil, errors.New("message cannot be empty")
	}

	k := pub.Size()

	maxLen := k - 11 // WARNING: why we subtract 11 from the size of the key
	if len(msg) > maxLen {
		return nil, errors.New("message too long")
	}

	// new function allocate the sized of the type in memory and return addr pointer
	m := new(big.Int).SetBytes(msg)
	if m.Cmp(new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), uint(k*8)), big.NewInt(1))) > 0 {
		return nil, errors.New("message too long for key size")
	}

	e := big.NewInt(int64(pub.E))
	c := modExp(m, e, pub.N)

	ciphertext := make([]byte, k)
	copy(ciphertext[k-len(c.Bytes()):], c.Bytes())
	return ciphertext, nil
}

func Decrypt(priv *RSAPrivateKey, ciphertext []byte) ([]byte, error) {
	if len(ciphertext) == 0 {
		return nil, errors.New("ciphertext cannot be empty")
	}

	if len(ciphertext) != priv.Size() {
		return nil, errors.New("ciphertext length mismatch")
	}

	c := new(big.Int).SetBytes(ciphertext)
	if c.Cmp(priv.N) >= 0 {
		return nil, errors.New("ciphertext too large")
	}

	m := modExp(c, priv.D, priv.N)

	return m.Bytes(), nil
}

func (pub *RSAPublicKey) Size() int {
	return (pub.N.BitLen() + 7) / 8
}

func (priv *RSAPrivateKey) Size() int {
	return (priv.N.BitLen() + 7) / 8
}

func (pub *RSAPublicKey) Marshal() string {
	nB64 := base64.StdEncoding.EncodeToString(pub.N.Bytes())
	eB64 := base64.StdEncoding.EncodeToString(big.NewInt(int64(pub.E)).Bytes())
	return nB64 + "|" + eB64
}

func UnmarshalPublicKey(s string) (*RSAPublicKey, error) {
	parts := make([]byte, 0, 512)
	parts = append(parts, []byte(s)...)

	delim := -1
	for i := 0; i < len(parts) && delim == -1; i++ {
		if parts[i] == '|' {
			delim = i
		}
	}
	if delim == -1 {
		return nil, errors.New("invalid key format")
	}

	nBytes, err := base64.StdEncoding.DecodeString(string(parts[:delim]))
	if err != nil {
		return nil, err
	}

	eBytes, err := base64.StdEncoding.DecodeString(string(parts[delim+1:]))
	if err != nil {
		return nil, err
	}

	n := new(big.Int).SetBytes(nBytes)
	e := int(new(big.Int).SetBytes(eBytes).Int64())

	return &RSAPublicKey{
		N: n,
		E: e,
	}, nil
}

func MarshalPrivateKey(priv *RSAPrivateKey) string {
	dB64 := base64.StdEncoding.EncodeToString(priv.D.Bytes())
	pB64 := base64.StdEncoding.EncodeToString(priv.Primes[0].Bytes())
	qB64 := base64.StdEncoding.EncodeToString(priv.Primes[1].Bytes())
	return dB64 + "|" + pB64 + "|" + qB64
}

func UnmarshalPrivateKey(s string) (*RSAPrivateKey, error) {
	parts := make([]byte, 0, 768)
	parts = append(parts, []byte(s)...)

	delim1, delim2 := -1, -1
	count := 0
	for i := 0; i < len(parts); i++ {
		if parts[i] == '|' {
			count++
			if count == 1 {
				delim1 = i
			} else if count == 2 {
				delim2 = i
				break
			}
		}
	}
	if delim1 == -1 || delim2 == -1 {
		return nil, errors.New("invalid key format")
	}

	dBytes, err := base64.StdEncoding.DecodeString(string(parts[:delim1]))
	if err != nil {
		return nil, err
	}

	pBytes, err := base64.StdEncoding.DecodeString(string(parts[delim1+1 : delim2]))
	if err != nil {
		return nil, err
	}

	qBytes, err := base64.StdEncoding.DecodeString(string(parts[delim2+1:]))
	if err != nil {
		return nil, err
	}

	d := new(big.Int).SetBytes(dBytes)
	p := new(big.Int).SetBytes(pBytes)
	q := new(big.Int).SetBytes(qBytes)

	n := new(big.Int).Mul(p, q)

	return &RSAPrivateKey{
		RSAPublicKey: RSAPublicKey{
			N: n,
			E: 65537,
		},
		D:      d,
		Primes: []*big.Int{p, q},
	}, nil
}
